export type VisualisationModeId =
  | 'terrain'
  | 'elevation'
  | 'surfaceAltitude'
  | 'waterDepth'
  | 'iceThickness'
  | 'salinity'
  | 'albedo'
  | 'solarFlux'
  | 'waterState'
  | 'surfaceTemperature'
  | 'atmosphericTemperature'
  | 'precipitableWater'
  | 'surfacePressure'
