/**
 * Generate pre-computed Planck spectral exitance lookup table
 *
 * Creates a 2D lookup table of Planck function values for all combinations
 * of wavelength bins and temperature range. This eliminates expensive
 * pow() and exp() calculations at runtime.
 *
 * Output: src/data/gasTextures/planckLookup.ts
 *
 * Physics: Planck's law is universal - independent of atmospheric composition.
 * The lookup table only depends on wavelength and temperature ranges.
 *
 * Usage: node scripts/generatePlanckLookup.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { getWavelengthBins, NUM_BINS } from './generateSpectralBins.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// === PHYSICS CONSTANTS ===
const PLANCK_CONST = 6.62607015e-34;  // J·s
const SPEED_OF_LIGHT = 299792458.0;   // m/s
const BOLTZMANN_CONST = 1.380649e-23; // J/K
const PI = Math.PI;

// === TEMPERATURE RANGE CONFIGURATION ===
const TEMP_MIN = 1;  // K (coldest expected planetary surface)
const TEMP_MAX = 1000; // K (hottest expected planetary surface)
const TEMP_STEP = 1;   // K (1 degree resolution)
const NUM_TEMPS = Math.floor((TEMP_MAX - TEMP_MIN) / TEMP_STEP) + 1;

/**
 * Calculates Planck spectral exitance.
 * M_λ(λ, T) = (2πhc² / λ⁵) / (e^(hc/λkT) - 1)
 *
 * @param wavelength_um Wavelength in micrometers
 * @param temperature_K Temperature in Kelvin
 * @returns Spectral exitance in W/(m²·μm)
 */
function planckSpectralExitance(wavelength_um, temperature_K) {
	const wavelength_m = wavelength_um * 1e-6;
	const numerator = 2.0 * PI * PLANCK_CONST * SPEED_OF_LIGHT * SPEED_OF_LIGHT;
	const wavelength5 = Math.pow(wavelength_m, 5.0);
	const exponent = (PLANCK_CONST * SPEED_OF_LIGHT) / (wavelength_m * BOLTZMANN_CONST * temperature_K);
	const denominator = wavelength5 * (Math.exp(exponent) - 1.0);
	const spectralRadiance = numerator / denominator;
	return spectralRadiance * PI * 1e-6; // W/(m²·μm)
}

/**
 * Generates Planck lookup table and writes to TypeScript file.
 */
function main() {
	console.log('Generating Planck lookup table...');
	console.log(`  Temperature range: ${TEMP_MIN}-${TEMP_MAX}K (${NUM_TEMPS} steps)`);
	console.log(`  Wavelength bins: ${NUM_BINS}`);

	// Get wavelength bins (shared with HITRAN processing)
	const wavelengths = getWavelengthBins();

	// Generate lookup table data
	const width = NUM_BINS;  // wavelength bins
	const height = NUM_TEMPS; // temperature samples
	const data = new Float32Array(width * height);

	let minValue = Infinity;
	let maxValue = -Infinity;

	for (let tempIdx = 0; tempIdx < NUM_TEMPS; tempIdx++) {
		const temperature = TEMP_MIN + tempIdx * TEMP_STEP;

		for (let wlIdx = 0; wlIdx < NUM_BINS; wlIdx++) {
			const wavelength = wavelengths[wlIdx];
			const exitance = planckSpectralExitance(wavelength, temperature);

			const dataIdx = tempIdx * width + wlIdx;
			data[dataIdx] = exitance;

			minValue = Math.min(minValue, exitance);
			maxValue = Math.max(maxValue, exitance);
		}
	}

	// Generate TypeScript file
	let content = '// Pre-computed Planck spectral exitance lookup table\n';
	content += '// Generated by scripts/generatePlanckLookup.js\n';

	content += `/** Planck lookup table configuration */\n`;
	content += `export const PLANCK_LOOKUP_CONFIG = {\n`;
	content += `\ttempMin: ${TEMP_MIN},  // K\n`;
	content += `\ttempMax: ${TEMP_MAX},  // K\n`;
	content += `\ttempStep: ${TEMP_STEP}, // K\n`;
	content += `\tnumTemps: ${NUM_TEMPS},\n`;
	content += `\tnumWavelengths: ${NUM_BINS}\n`;
	content += `} as const;\n\n`;

	content += `/** Planck lookup table data (${width}×${height}, W/(m²·μm)) */\n`;
	content += 'export const planckLookupData = new Float32Array([\n\t';
	content += Array.from(data).map(v => v.toExponential(6)).join(', ');
	content += '\n]);\n';

	// Write output file
	const outputDir = path.join(__dirname, '..', 'src', 'data', 'gasTextures');
	if (!fs.existsSync(outputDir)) {
		fs.mkdirSync(outputDir, { recursive: true });
	}

	const outputPath = path.join(outputDir, 'planckLookup.ts');
	fs.writeFileSync(outputPath, content, 'utf8');

	console.log(`Planck lookup table: ${width}×${height} (${data.byteLength.toLocaleString()} bytes)`);
	console.log(`  Temperature range: ${TEMP_MIN}-${TEMP_MAX}K`);
	console.log(`  Value range: ${minValue.toExponential(3)} - ${maxValue.toExponential(3)} W/(m²·μm)`);
	console.log(`  Written to: ${outputPath}`);
}

main();
